//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentAuction.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainFormInitialLocation {
            get {
                return ((string)(this["MainFormInitialLocation"]));
            }
            set {
                this["MainFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ItemsItemDescriptionColumnWidth {
            get {
                return ((int)(this["ItemsItemDescriptionColumnWidth"]));
            }
            set {
                this["ItemsItemDescriptionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ItemsDonorIdColumnWidth {
            get {
                return ((int)(this["ItemsDonorIdColumnWidth"]));
            }
            set {
                this["ItemsDonorIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ItemsNameColumnWidth {
            get {
                return ((int)(this["ItemsNameColumnWidth"]));
            }
            set {
                this["ItemsNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int ItemsQtyColumnWidth {
            get {
                return ((int)(this["ItemsQtyColumnWidth"]));
            }
            set {
                this["ItemsQtyColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ItemsNotesColumnWidth {
            get {
                return ((int)(this["ItemsNotesColumnWidth"]));
            }
            set {
                this["ItemsNotesColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ItemsRetailValueColumnWidth {
            get {
                return ((int)(this["ItemsRetailValueColumnWidth"]));
            }
            set {
                this["ItemsRetailValueColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int ItemsBuyItNowValueColumnWidth {
            get {
                return ((int)(this["ItemsBuyItNowValueColumnWidth"]));
            }
            set {
                this["ItemsBuyItNowValueColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int ItemsBidIncrementTypeColumnWidth {
            get {
                return ((int)(this["ItemsBidIncrementTypeColumnWidth"]));
            }
            set {
                this["ItemsBidIncrementTypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int ItemsBidMinColumnWidth {
            get {
                return ((int)(this["ItemsBidMinColumnWidth"]));
            }
            set {
                this["ItemsBidMinColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int ItemsBidMaxColumnWidth {
            get {
                return ((int)(this["ItemsBidMaxColumnWidth"]));
            }
            set {
                this["ItemsBidMaxColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int ItemsBidNumberOfBidsColumnWidth {
            get {
                return ((int)(this["ItemsBidNumberOfBidsColumnWidth"]));
            }
            set {
                this["ItemsBidNumberOfBidsColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ItemsBidIncrementValuesColumnWidth {
            get {
                return ((int)(this["ItemsBidIncrementValuesColumnWidth"]));
            }
            set {
                this["ItemsBidIncrementValuesColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsDonorTypeColumnWidth {
            get {
                return ((int)(this["DonorsDonorTypeColumnWidth"]));
            }
            set {
                this["DonorsDonorTypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsNameColumnWidth {
            get {
                return ((int)(this["DonorsNameColumnWidth"]));
            }
            set {
                this["DonorsNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsContactNameColumnWidth {
            get {
                return ((int)(this["DonorsContactNameColumnWidth"]));
            }
            set {
                this["DonorsContactNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsStreet1ColumnWidth {
            get {
                return ((int)(this["DonorsStreet1ColumnWidth"]));
            }
            set {
                this["DonorsStreet1ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsStreet2ColumnWidth {
            get {
                return ((int)(this["DonorsStreet2ColumnWidth"]));
            }
            set {
                this["DonorsStreet2ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsCityColumnWidth {
            get {
                return ((int)(this["DonorsCityColumnWidth"]));
            }
            set {
                this["DonorsCityColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsStateColumnWidth {
            get {
                return ((int)(this["DonorsStateColumnWidth"]));
            }
            set {
                this["DonorsStateColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsZipCodeColumnWidth {
            get {
                return ((int)(this["DonorsZipCodeColumnWidth"]));
            }
            set {
                this["DonorsZipCodeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsPhone1ColumnWidth {
            get {
                return ((int)(this["DonorsPhone1ColumnWidth"]));
            }
            set {
                this["DonorsPhone1ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsExt1ColumnWidth {
            get {
                return ((int)(this["DonorsExt1ColumnWidth"]));
            }
            set {
                this["DonorsExt1ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsPhone2ColumnWidth {
            get {
                return ((int)(this["DonorsPhone2ColumnWidth"]));
            }
            set {
                this["DonorsPhone2ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsExt2ColumnWidth {
            get {
                return ((int)(this["DonorsExt2ColumnWidth"]));
            }
            set {
                this["DonorsExt2ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsEmailColumnWidth {
            get {
                return ((int)(this["DonorsEmailColumnWidth"]));
            }
            set {
                this["DonorsEmailColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int AuctionsNameColumnWidth {
            get {
                return ((int)(this["AuctionsNameColumnWidth"]));
            }
            set {
                this["AuctionsNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int AuctionsDescriptionColumnWidth {
            get {
                return ((int)(this["AuctionsDescriptionColumnWidth"]));
            }
            set {
                this["AuctionsDescriptionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SilentAuction.sqlite")]
        public string SilentAuctionDatabaseName {
            get {
                return ((string)(this["SilentAuctionDatabaseName"]));
            }
            set {
                this["SilentAuctionDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\"C:\\_My Projects\\SilentAuction\\SilentAuction\\bin\\Debug\\SilentAuction." +
            "sqlite\"")]
        public string SilentAuctionConnectionString {
            get {
                return ((string)(this["SilentAuctionConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsRequestFormatTypeIdColumnWidth {
            get {
                return ((int)(this["DonorsRequestFormatTypeIdColumnWidth"]));
            }
            set {
                this["DonorsRequestFormatTypeIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int DonorsUrlColumnWidth {
            get {
                return ((int)(this["DonorsUrlColumnWidth"]));
            }
            set {
                this["DonorsUrlColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ItemsItemTypeIdColumnWidth {
            get {
                return ((int)(this["ItemsItemTypeIdColumnWidth"]));
            }
            set {
                this["ItemsItemTypeIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ItemsDonationDeliveryTypeIdColumnWidth {
            get {
                return ((int)(this["ItemsDonationDeliveryTypeIdColumnWidth"]));
            }
            set {
                this["ItemsDonationDeliveryTypeIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditDonorListInitialLocation {
            get {
                return ((string)(this["EditDonorListInitialLocation"]));
            }
            set {
                this["EditDonorListInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditAuctionListInitialLocation {
            get {
                return ((string)(this["EditAuctionListInitialLocation"]));
            }
            set {
                this["EditAuctionListInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AuctionIdInUse {
            get {
                return ((int)(this["AuctionIdInUse"]));
            }
            set {
                this["AuctionIdInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AuctionNameInUse {
            get {
                return ((string)(this["AuctionNameInUse"]));
            }
            set {
                this["AuctionNameInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DonorsRequestStatusTypeIdColumnWidth {
            get {
                return ((int)(this["DonorsRequestStatusTypeIdColumnWidth"]));
            }
            set {
                this["DonorsRequestStatusTypeIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentEditorInitialLocation {
            get {
                return ((string)(this["DocumentEditorInitialLocation"]));
            }
            set {
                this["DocumentEditorInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShowAllItemsByDonorNamesInitialLocation {
            get {
                return ((string)(this["ShowAllItemsByDonorNamesInitialLocation"]));
            }
            set {
                this["ShowAllItemsByDonorNamesInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CreateAuctionInitialLocation {
            get {
                return ((string)(this["CreateAuctionInitialLocation"]));
            }
            set {
                this["CreateAuctionInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CopyDonorsInitialLocation {
            get {
                return ((string)(this["CopyDonorsInitialLocation"]));
            }
            set {
                this["CopyDonorsInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintFormInitialLocation {
            get {
                return ((string)(this["PrintFormInitialLocation"]));
            }
            set {
                this["PrintFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditAuctionFormInitialLocation {
            get {
                return ((string)(this["EditAuctionFormInitialLocation"]));
            }
            set {
                this["EditAuctionFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CreateDonorInitialLocation {
            get {
                return ((string)(this["CreateDonorInitialLocation"]));
            }
            set {
                this["CreateDonorInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAuctionInitialLocation {
            get {
                return ((string)(this["OpenAuctionInitialLocation"]));
            }
            set {
                this["OpenAuctionInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoResponseByDonorInitialLocation {
            get {
                return ((string)(this["NoResponseByDonorInitialLocation"]));
            }
            set {
                this["NoResponseByDonorInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ItemsImageColumnWidth {
            get {
                return ((int)(this["ItemsImageColumnWidth"]));
            }
            set {
                this["ItemsImageColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailFormInitialLocation {
            get {
                return ((string)(this["EmailFormInitialLocation"]));
            }
            set {
                this["EmailFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateAddressLabelsFileInitialLocation {
            get {
                return ((string)(this["GenerateAddressLabelsFileInitialLocation"]));
            }
            set {
                this["GenerateAddressLabelsFileInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ItemsIdColumnWidth {
            get {
                return ((int)(this["ItemsIdColumnWidth"]));
            }
            set {
                this["ItemsIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectItemsFormInitialLocation {
            get {
                return ((string)(this["SelectItemsFormInitialLocation"]));
            }
            set {
                this["SelectItemsFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentNameEntryInitialLocation {
            get {
                return ((string)(this["DocumentNameEntryInitialLocation"]));
            }
            set {
                this["DocumentNameEntryInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentOpenFormInitialLocation {
            get {
                return ((string)(this["DocumentOpenFormInitialLocation"]));
            }
            set {
                this["DocumentOpenFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BidCalculatorFormInitialLocation {
            get {
                return ((string)(this["BidCalculatorFormInitialLocation"]));
            }
            set {
                this["BidCalculatorFormInitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CreateItemInitialLocation {
            get {
                return ((string)(this["CreateItemInitialLocation"]));
            }
            set {
                this["CreateItemInitialLocation"] = value;
            }
        }
    }
}
