//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentAuction.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialLocation {
            get {
                return ((string)(this["InitialLocation"]));
            }
            set {
                this["InitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ItemsItemDescriptionColumnWidth {
            get {
                return ((int)(this["ItemsItemDescriptionColumnWidth"]));
            }
            set {
                this["ItemsItemDescriptionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ItemsDonorIdColumnWidth {
            get {
                return ((int)(this["ItemsDonorIdColumnWidth"]));
            }
            set {
                this["ItemsDonorIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ItemsNameColumnWidth {
            get {
                return ((int)(this["ItemsNameColumnWidth"]));
            }
            set {
                this["ItemsNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int ItemsQtyColumnWidth {
            get {
                return ((int)(this["ItemsQtyColumnWidth"]));
            }
            set {
                this["ItemsQtyColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ItemsNotesColumnWidth {
            get {
                return ((int)(this["ItemsNotesColumnWidth"]));
            }
            set {
                this["ItemsNotesColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ItemsRetailValueColumnWidth {
            get {
                return ((int)(this["ItemsRetailValueColumnWidth"]));
            }
            set {
                this["ItemsRetailValueColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int ItemsBuyItNowValueColumnWidth {
            get {
                return ((int)(this["ItemsBuyItNowValueColumnWidth"]));
            }
            set {
                this["ItemsBuyItNowValueColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int ItemsBidIncrementTypeColumnWidth {
            get {
                return ((int)(this["ItemsBidIncrementTypeColumnWidth"]));
            }
            set {
                this["ItemsBidIncrementTypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int ItemsBidMinColumnWidth {
            get {
                return ((int)(this["ItemsBidMinColumnWidth"]));
            }
            set {
                this["ItemsBidMinColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int ItemsBidMaxColumnWidth {
            get {
                return ((int)(this["ItemsBidMaxColumnWidth"]));
            }
            set {
                this["ItemsBidMaxColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int ItemsBidNumberOfBidsColumnWidth {
            get {
                return ((int)(this["ItemsBidNumberOfBidsColumnWidth"]));
            }
            set {
                this["ItemsBidNumberOfBidsColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ItemsBidIncrementValuesColumnWidth {
            get {
                return ((int)(this["ItemsBidIncrementValuesColumnWidth"]));
            }
            set {
                this["ItemsBidIncrementValuesColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsDonorTypeColumnWidth {
            get {
                return ((int)(this["DonorsDonorTypeColumnWidth"]));
            }
            set {
                this["DonorsDonorTypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsNameColumnWidth {
            get {
                return ((int)(this["DonorsNameColumnWidth"]));
            }
            set {
                this["DonorsNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsContactNameColumnWidth {
            get {
                return ((int)(this["DonorsContactNameColumnWidth"]));
            }
            set {
                this["DonorsContactNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsStreet1ColumnWidth {
            get {
                return ((int)(this["DonorsStreet1ColumnWidth"]));
            }
            set {
                this["DonorsStreet1ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsStreet2ColumnWidth {
            get {
                return ((int)(this["DonorsStreet2ColumnWidth"]));
            }
            set {
                this["DonorsStreet2ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsCityColumnWidth {
            get {
                return ((int)(this["DonorsCityColumnWidth"]));
            }
            set {
                this["DonorsCityColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsStateColumnWidth {
            get {
                return ((int)(this["DonorsStateColumnWidth"]));
            }
            set {
                this["DonorsStateColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsZipCodeColumnWidth {
            get {
                return ((int)(this["DonorsZipCodeColumnWidth"]));
            }
            set {
                this["DonorsZipCodeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsPhone1ColumnWidth {
            get {
                return ((int)(this["DonorsPhone1ColumnWidth"]));
            }
            set {
                this["DonorsPhone1ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsExt1ColumnWidth {
            get {
                return ((int)(this["DonorsExt1ColumnWidth"]));
            }
            set {
                this["DonorsExt1ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsPhone2ColumnWidth {
            get {
                return ((int)(this["DonorsPhone2ColumnWidth"]));
            }
            set {
                this["DonorsPhone2ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsExt2ColumnWidth {
            get {
                return ((int)(this["DonorsExt2ColumnWidth"]));
            }
            set {
                this["DonorsExt2ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DonorsEmailColumnWidth {
            get {
                return ((int)(this["DonorsEmailColumnWidth"]));
            }
            set {
                this["DonorsEmailColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int AuctionsNameColumnWidth {
            get {
                return ((int)(this["AuctionsNameColumnWidth"]));
            }
            set {
                this["AuctionsNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int AuctionsDescriptionColumnWidth {
            get {
                return ((int)(this["AuctionsDescriptionColumnWidth"]));
            }
            set {
                this["AuctionsDescriptionColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SilentAuction.sqlite")]
        public string SilentAuctionDatabaseName {
            get {
                return ((string)(this["SilentAuctionDatabaseName"]));
            }
            set {
                this["SilentAuctionDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\"C:\\_My Projects\\SilentAuction\\SilentAuction\\bin\\Debug\\SilentAuction." +
            "sqlite\"")]
        public string SilentAuctionConnectionString {
            get {
                return ((string)(this["SilentAuctionConnectionString"]));
            }
        }
    }
}
